version: 2

jobs:
  build:
    machine:
        enabled: true
    steps:
      - run:
          name: Install Nix
          command: |
            sudo mkdir -p /nix
            sudo chown circleci /nix
            bash <(curl https://nixos.org/nix/install)
            echo '. /home/circleci/.nix-profile/etc/profile.d/nix.sh' >> $BASH_ENV
            sudo mkdir -p /etc/nix

            # Enable sandbox
            echo "build-use-sandbox = true" | sudo tee -a /etc/nix/nix.conf

      - checkout

      - run:
          name: Build
          command: |
            nix-build --no-link --sandbox --max-jobs 20

            mkdir -p /tmp
            cp $(nix-build -A pdf)/resume.pdf /tmp/resume.pdf
            cp $(nix-build -A html)/resume.html /tmp/resume.html

      - store_artifacts:
          path: /tmp/resume.pdf

      - store_artifacts:
          path: /tmp/resume.html

workflows:
  version: 2
  build:
    jobs:
      - build
